steps:
  - label: "Build and Push Multiarch App"
    commands: |
      echo "Starting multiarch build as buildkite-agent user"
      docker buildx rm mybuilder || true
      docker buildx create --use --name mybuilder
      docker buildx inspect --bootstrap
      docker buildx build --platform linux/amd64,linux/arm64 -t {$DOCKER_USERNAME}/multi-arch-app:latest --push .
    agents:
      queue: arm64
    env:
    #  DOCKER_USERNAME: "$DOCKER_USERNAME"
     # DOCKER_PASSWORD: "$DOCKER_PASSWORD"
      #DOCKER_CONFIG: "$DOCKER_CONFIG"
