steps:
  - label: "Build and Push Multiarch App"
    commands: |
      echo "Checking the build environment..."
      echo "HOOK_TRIGGER_TEST = $HOOK_TRIGGER_TEST"
      env | grep DOCKER_
      whoami
      echo $DOCKER_USERNAME
      # Clean up and set up buildx
      docker buildx rm mybuilder || true
      docker buildx create --use --name mybuilder
      docker buildx inspect --bootstrap

      # Login and build
      docker login
      docker buildx build --platform linux/amd64,linux/arm64 \
      -t "$DOCKER_USERNAME/multi-arch-app:latest" --push .

    agents:
      queue: arm64
